"""游戏领域热门元素词库：主流游戏的角色名、术语与圈内梗。"""

TOPICS = [
    {"name": "三角洲行动", "category": "game", "desc": "腾讯战术射击游戏，分烽火地带撤离和全面战场两种玩法", "aliases": ["三角洲行动", "三角洲", "delta force"]},
    {"name": "烽火地带", "category": "game_term", "desc": "三角洲行动的撤离玩法，带装备进场、活着带出战利品", "aliases": ["烽火地带", "烽火"]},
    {"name": "全面战场", "category": "game_term", "desc": "三角洲行动的大战场玩法，载具兵种齐上阵的大规模对抗", "aliases": ["全面战场"]},
    {"name": "密令", "category": "game_term", "desc": "三角洲行动的高难关卡模式，风险更大但回报也更丰厚", "aliases": ["密令", "机密行动"]},
    {"name": "撤离", "category": "game_term", "desc": "带着搜刮到的物资从地图指定撤离点安全撤出", "aliases": ["撤离", "撤离点"]},
    {"name": "零号大坝", "category": "game_term", "desc": "三角洲行动经典地图，中间是水坝建筑群、资源集中", "aliases": ["零号大坝", "大坝"]},
    {"name": "巴克什", "category": "game_term", "desc": "三角洲行动的沙漠城镇地图，房屋密集适合近战", "aliases": ["巴克什"]},
    {"name": "长弓溪谷", "category": "game_term", "desc": "三角洲行动的山谷地图，地形起伏、适合远程架枪", "aliases": ["长弓溪谷", "长弓"]},
    {"name": "航天基地", "category": "game_term", "desc": "三角洲行动的航天主题地图，建筑大、物资多", "aliases": ["航天基地"]},
    {"name": "红狼", "category": "game_char", "desc": "《三角洲行动》的突击干员，机动性强、适合冲锋开路", "aliases": ["红狼"]},
    {"name": "威龙", "category": "game_char", "desc": "《三角洲行动》的干员，擅重火力压制与正面刚枪", "aliases": ["威龙"]},
    {"name": "露娜", "category": "game_char", "desc": "《三角洲行动》的女性干员，擅侦察与情报支援", "aliases": ["露娜"]},
    {"name": "比特", "category": "game_char", "desc": "《三角洲行动》的干员，用科技手段辅助团队作战", "aliases": ["比特"]},
    {"name": "蜂医", "category": "game_char", "desc": "《三角洲行动》的医疗干员，负责回血和扶起倒地队友", "aliases": ["蜂医"]},
    {"name": "牧羊人", "category": "game_char", "desc": "《三角洲行动》的支援干员，能放庇护装置护住队友", "aliases": ["牧羊人"]},
    {"name": "蜂刺", "category": "game_char", "desc": "《三角洲行动》的突击干员，主打近身突进与爆发", "aliases": ["蜂刺"]},
    {"name": "乌兹", "category": "game_char", "desc": "《三角洲行动》的干员，机动灵活、擅长游击打法", "aliases": ["乌兹"]},
    {"name": "枪匠", "category": "game_term", "desc": "三角洲行动的武器改装系统，可自由搭配配件改枪", "aliases": ["枪匠"]},
    {"name": "护甲", "category": "game_term", "desc": "抵挡子弹伤害的装备，按防护能力分不同等级", "aliases": ["护甲"]},
    {"name": "攒点", "category": "game_term", "desc": "慢慢积攒游戏积分求稳发育，不急着正面开战", "aliases": ["攒点"]},
    {"name": "卡点", "category": "game_term", "desc": "提前守在地图关键位置，卡住对手必经之路", "aliases": ["卡点"]},
    {"name": "白给", "category": "game_term", "desc": "白白送人头，把好装备和人头拱手送给对手", "aliases": ["白给"]},
    {"name": "架枪", "category": "game_term", "desc": "举枪对准通道或转角，等对手露头再打", "aliases": ["架枪"]},
    {"name": "舔包", "category": "game_term", "desc": "击杀对手后搜刮其掉落的装备物资", "aliases": ["舔包"]},
    {"name": "摸金", "category": "game_term", "desc": "专门跑图搜刮高价值物资、追求赚钱的打法", "aliases": ["摸金", "摸金校尉"]},
    {"name": "红卡", "category": "game_term", "desc": "三角洲行动里高价值的门禁卡，一张能卖不少钱", "aliases": ["红卡"]},
    {"name": "安全箱", "category": "game_term", "desc": "死亡也不会丢失的保底储物格，常装最贵的物资", "aliases": ["安全箱"]},
    {"name": "平头哥", "category": "game_term", "desc": "指一头扎进枪林弹雨硬刚的莽夫玩家", "aliases": ["平头哥"]},
    {"name": "送快递", "category": "game_term", "desc": "带一身好装备出门，没多久就被打死让人捡走", "aliases": ["送快递"]},
    {"name": "一穿三", "category": "game_term", "desc": "一个人连续击杀对面三人，打出高光操作", "aliases": ["一穿三"]},
    {"name": "干拉", "category": "game_term", "desc": "不丢烟不探信息，直接迎面冲上去打的莽夫行为", "aliases": ["干拉"]},
    {"name": "报点", "category": "game_term", "desc": "把敌人位置、人数等情报快速喊给队友", "aliases": ["报点"]},
    {"name": "压枪", "category": "game_term", "desc": "连续射击时下压鼠标，抵消枪口上抬让子弹更准", "aliases": ["压枪"]},
    {"name": "大金", "category": "game_term", "desc": "地图里价值最高的金色物资，捡到就等于发大财", "aliases": ["大金"]},
    {"name": "六套", "category": "game_term", "desc": "最高等级的六件套装备，穿上就是行走的五花肉", "aliases": ["六套"]},
    {"name": "开箱", "category": "game_term", "desc": "打开地图上的箱子或补给，搜刮里面的物资", "aliases": ["开箱"]},
    {"name": "打药", "category": "game_term", "desc": "战斗中给自己或队友补血、回状态的简称", "aliases": ["打药", "嗑药"]},

    {"name": "无畏契约", "category": "game", "desc": "拳头 5v5 战术射击游戏，国服叫无畏契约、玩家俗称瓦", "aliases": ["无畏契约", "瓦罗兰特", "valorant"]},
    {"name": "捷风", "category": "game_char", "desc": "《无畏契约》决斗者，能高速位移、灵活切入", "aliases": ["捷风", "jett"]},
    {"name": "贤者", "category": "game_char", "desc": "《无畏契约》哨位，能造墙放减速还可用技能复活队友", "aliases": ["贤者", "sage"]},
    {"name": "幽影", "category": "game_char", "desc": "《无畏契约》控场者，能放烟并短距传送偷袭", "aliases": ["幽影", "omen"]},
    {"name": "雷兹", "category": "game_char", "desc": "《无畏契约》决斗者，玩炸弹和火箭筒的爆破手", "aliases": ["雷兹", "raze"]},
    {"name": "不死鸟", "category": "game_char", "desc": "《无畏契约》决斗者，能自燃回血、放火墙封路", "aliases": ["不死鸟", "phoenix"]},
    {"name": "猎枭", "category": "game_char", "desc": "《无畏契约》情报位，射震荡箭和侦查箭来探信息", "aliases": ["猎枭", "sova"]},
    {"name": "圣祈", "category": "game_char", "desc": "《无畏契约》先锋，能放治疗、探路鹰和闪光", "aliases": ["圣祈", "skye"]},
    {"name": "瑞娜", "category": "game_char", "desc": "《无畏契约》决斗者，靠击杀灵魂回血、开大变更强", "aliases": ["瑞娜", "reyna"]},
    {"name": "零", "category": "game_char", "desc": "《无畏契约》情报位，放摄像头和绊线封锁地图", "aliases": ["cypher"]},
    {"name": "霓虹", "category": "game_char", "desc": "《无畏契约》决斗者，高速冲刺放电、速度感极强", "aliases": ["霓虹", "neon"]},
    {"name": "钱博", "category": "game_char", "desc": "《无畏契约》哨位，靠金枪和传送点看家守点", "aliases": ["钱博", "chamber"]},
    {"name": "盖可", "category": "game_char", "desc": "《无畏契约》先锋，带一群小宠物丢闪光和炸弹", "aliases": ["盖可", "gekko"]},
    {"name": "死锁", "category": "game_char", "desc": "《无畏契约》哨位，放重力网和声波网封锁冲锋", "aliases": ["死锁", "deadlock"]},
    {"name": "ISO", "category": "game_char", "desc": "《无畏契约》决斗者，开护盾单挑、越打越强", "aliases": ["iso"]},
    {"name": "布史东", "category": "game_char", "desc": "《无畏契约》控场者，老队长，能放烟雾和轨道轰炸", "aliases": ["布史东", "brimstone"]},
    {"name": "蝰蛇", "category": "game_char", "desc": "《无畏契约》控场者，用毒墙和毒气分割战场", "aliases": ["蝰蛇", "viper"]},
    {"name": "经济局", "category": "game_term", "desc": "没钱只能买手枪或半甲的省吃俭用回合", "aliases": ["经济局", "eco"]},
    {"name": "点内", "category": "game_term", "desc": "炸弹安放区里面的位置，进攻方要冲进去占住", "aliases": ["点内", "包点"]},
    {"name": "假打", "category": "game_term", "desc": "佯攻一个点吸引敌人，实际转去打另一个点", "aliases": ["假打"]},
    {"name": "爆头", "category": "game_term", "desc": "一枪打中头部造成高额伤害、往往直接秒杀", "aliases": ["爆头"]},
    {"name": "烟雾弹", "category": "game_term", "desc": "扔出后形成烟幕，遮挡视线封锁枪线", "aliases": ["烟雾弹", "烟雾"]},
    {"name": "残局", "category": "game_term", "desc": "队友都倒下后一人面对多个敌人的收拾局面", "aliases": ["残局"]},
    {"name": "架点", "category": "game_term", "desc": "守在关键位置对准来路，等敌人送上门", "aliases": ["架点"]},
    {"name": "大狙", "category": "game_term", "desc": "无畏契约里的狙击枪，一枪毙命、价值很高", "aliases": ["大狙", "狙击枪"]},
    {"name": "拆包", "category": "game_term", "desc": "防守方在炸弹爆炸之前把它安全拆除", "aliases": ["拆包"]},
    {"name": "Ace", "category": "game_term", "desc": "一回合内单人击杀对面全部五人的神操作", "aliases": ["ace"]},
    {"name": "赛点", "category": "game_term", "desc": "先拿到赛点的一方再赢一局就拿下比赛", "aliases": ["赛点"]},
    {"name": "VCT", "category": "game_term", "desc": "无畏契约冠军巡回赛，官方最高级别赛事体系", "aliases": ["vct"]},
    {"name": "CN瓦", "category": "game_term", "desc": "中国赛区的无畏契约圈，也指国服玩家群体", "aliases": ["cn瓦"]},
    {"name": "腾竞", "category": "game_term", "desc": "腾讯电竞的简称，国内多项电竞赛事的运营方", "aliases": ["腾竞"]},
    {"name": "瓦学妹", "category": "game_term", "desc": "调侃玩无畏契约的女玩家，弹幕里的玩梗称呼", "aliases": ["瓦学妹"]},

    {"name": "英雄联盟", "category": "game", "desc": "拳头 5v5 MOBA 端游，全球最火的电竞项目之一", "aliases": ["英雄联盟", "lol"]},
    {"name": "亚索", "category": "game_char", "desc": "《英雄联盟》疾风剑豪，能连招位移、被戏称快乐风男", "aliases": ["亚索", "yasuo"]},
    {"name": "劫", "category": "game_char", "desc": "《英雄联盟》影流之主，用影分身切入秒杀后排", "aliases": ["zed"]},
    {"name": "盖伦", "category": "game_char", "desc": "《英雄联盟》德玛西亚之力，新手入门英雄、能转圈", "aliases": ["盖伦", "garen"]},
    {"name": "锐雯", "category": "game_char", "desc": "《英雄联盟》放逐之刃，光速连招、操作上限高", "aliases": ["锐雯", "riven"]},
    {"name": "艾希", "category": "game_char", "desc": "《英雄联盟》寒冰射手，平 A 输出、大招全图开团", "aliases": ["艾希", "ashe"]},
    {"name": "金克丝", "category": "game_char", "desc": "《英雄联盟》暴走萝莉，攻速起来后火力凶猛", "aliases": ["金克丝", "jinx"]},
    {"name": "永恩", "category": "game_char", "desc": "《英雄联盟》封魔剑魂，亚索的哥哥，能突进收割", "aliases": ["永恩", "yone"]},
    {"name": "厄斐琉斯", "category": "game_char", "desc": "《英雄联盟》残月之肃，五把武器轮换、门槛高", "aliases": ["厄斐琉斯", "aphelios"]},
    {"name": "卡莎", "category": "game_char", "desc": "《英雄联盟》虚空之女，能进化技能、后期射手", "aliases": ["卡莎", "kaisa"]},
    {"name": "盲僧", "category": "game_char", "desc": "《英雄联盟》李青，招牌摸眼回旋踢、打野常青树", "aliases": ["盲僧", "lee sin"]},
    {"name": "亚托克斯", "category": "game_char", "desc": "《英雄联盟》暗裔剑魔，能吸血复活的战士", "aliases": ["亚托克斯", "剑魔", "aatrox"]},
    {"name": "薇恩", "category": "game_char", "desc": "《英雄联盟》暗夜猎手，靠三环真伤收割的射手", "aliases": ["薇恩", "vayne"]},
    {"name": "ez", "category": "game_char", "desc": "《英雄联盟》探险家伊泽瑞尔，弹幕常直接喊 ez", "aliases": ["ezreal"]},
    {"name": "锤石", "category": "game_char", "desc": "《英雄联盟》魂锁典狱长，钩子和灯笼的招牌辅助", "aliases": ["锤石", "thresh"]},
    {"name": "莫甘娜", "category": "game_char", "desc": "《英雄联盟》堕落天使，黑盾免控、团控专家", "aliases": ["莫甘娜", "morgana"]},
    {"name": "佛耶戈", "category": "game_char", "desc": "《英雄联盟》破败之王，击杀后能夺舍对手英雄", "aliases": ["佛耶戈", "viego"]},
    {"name": "提莫", "category": "game_char", "desc": "《英雄联盟》迅捷斥候，种蘑菇阴人、最招人恨英雄", "aliases": ["提莫", "teemo"]},
    {"name": "剑圣", "category": "game_char", "desc": "《英雄联盟》无极剑圣易大师，开大招追杀收割", "aliases": ["剑圣", "master yi"]},
    {"name": "石头人", "category": "game_char", "desc": "《英雄联盟》熔岩巨兽墨菲特，团控大招一撞一群", "aliases": ["石头人", "malphite"]},
    {"name": "打野", "category": "game_term", "desc": "在野区刷野升级、游走支援各路的定位", "aliases": ["打野"]},
    {"name": "上单", "category": "game_term", "desc": "单人走上路的定位，多为坦克或战士", "aliases": ["上单"]},
    {"name": "中单", "category": "game_term", "desc": "单人走中路、负责游走带节奏的定位", "aliases": ["中单"]},
    {"name": "ADC", "category": "game_term", "desc": "下路远程物理输出核心，后期团队主要伤害来源", "aliases": ["adc"]},
    {"name": "辅助", "category": "game_term", "desc": "陪 ADC 走下路、负责保护与开视野的定位", "aliases": ["辅助"]},
    {"name": "gank", "category": "game_term", "desc": "打野或队友突然从侧面包夹抓人的战术", "aliases": ["gank"]},
    {"name": "控龙", "category": "game_term", "desc": "争夺并击杀小龙大龙，为团队拿增益", "aliases": ["控龙", "打龙"]},
    {"name": "团战", "category": "game_term", "desc": "双方五个人正面开打的大规模混战", "aliases": ["团战"]},
    {"name": "四保一", "category": "game_term", "desc": "四个人保护一个核心输出的战术体系", "aliases": ["四保一"]},
    {"name": "对线", "category": "game_term", "desc": "前期在线上清兵、换血、压制对手的阶段", "aliases": ["对线"]},
    {"name": "补刀", "category": "game_term", "desc": "打最后一下击杀小兵拿金币的基本功", "aliases": ["补刀"]},
    {"name": "BAN", "category": "game_term", "desc": "禁选环节禁用英雄，防止对手拿到招牌", "aliases": ["ban"]},
    {"name": "PICK", "category": "game_term", "desc": "禁选环节挑选自己这一局要用的英雄", "aliases": ["pick"]},
    {"name": "双边", "category": "game_term", "desc": "指两边双人路的对线，也泛指上下两路的博弈", "aliases": ["双边"]},
    {"name": "闪现", "category": "game_term", "desc": "通用召唤师技能，瞬间位移一段距离", "aliases": ["闪现"]},
    {"name": "五杀", "category": "game_term", "desc": "一个人连续击杀对面全部五名英雄的高光", "aliases": ["五杀", "penta"]},
    {"name": "超神", "category": "game_term", "desc": "连续击杀到 8 个以上不死，弹幕会刷屏称赞", "aliases": ["超神"]},
    {"name": "LPL", "category": "game_term", "desc": "英雄联盟职业联赛中国大陆赛区，国内最高级别赛事", "aliases": ["lpl"]},
    {"name": "S赛", "category": "game_term", "desc": "英雄联盟全球总决赛，一年一度的最高荣誉", "aliases": ["s赛", "全球总决赛"]},
    {"name": "MSI", "category": "game_term", "desc": "英雄联盟季中冠军赛，各赛区冠军对决", "aliases": ["msi"]},
    {"name": "韩援", "category": "game_term", "desc": "来自韩国的外援选手，LPL 战队常见配置", "aliases": ["韩援"]},
    {"name": "全华班", "category": "game_term", "desc": "全部由中国选手组成的战队阵容配置", "aliases": ["全华班"]},
    {"name": "TES", "category": "game_term", "desc": "滔搏电子竞技俱乐部，LPL 知名战队", "aliases": ["tes"]},
    {"name": "BLG", "category": "game_term", "desc": "哔哩哔哩电子竞技俱乐部，LPL 人气战队", "aliases": ["blg"]},
    {"name": "JDG", "category": "game_term", "desc": "京东星宇电子竞技俱乐部，LPL 强队", "aliases": ["jdg"]},
    {"name": "德杯", "category": "game_term", "desc": "德玛西亚杯，LPL 各队参加的国内赛事", "aliases": ["德杯"]},

    {"name": "王者荣耀", "category": "game", "desc": "腾讯 5v5 手游 MOBA，国内用户量最大的手机游戏", "aliases": ["王者荣耀", "王者"]},
    {"name": "安琪拉", "category": "game_char", "desc": "《王者荣耀》法师，技能连招伤害高、新手爱用", "aliases": ["安琪拉"]},
    {"name": "妲己", "category": "game_char", "desc": "《王者荣耀》法师，锁定技能加高爆发、蹲草秒人", "aliases": ["妲己"]},
    {"name": "鲁班七号", "category": "game_char", "desc": "《王者荣耀》射手，个子矮输出高、常被对面针对", "aliases": ["鲁班七号", "鲁班"]},
    {"name": "后羿", "category": "game_char", "desc": "《王者荣耀》射手，普攻流、大招全图定人", "aliases": ["后羿"]},
    {"name": "花木兰", "category": "game_char", "desc": "《王者荣耀》战士，双形态切换、操作上限高", "aliases": ["花木兰"]},
    {"name": "李白", "category": "game_char", "desc": "《王者荣耀》刺客，技能帅、大招无敌帧多", "aliases": ["李白"]},
    {"name": "韩信", "category": "game_char", "desc": "《王者荣耀》刺客，位移多、跑图带节奏的野王", "aliases": ["韩信"]},
    {"name": "貂蝉", "category": "game_char", "desc": "《王者荣耀》法师，开大减速黏人、团战收割", "aliases": ["貂蝉"]},
    {"name": "马超", "category": "game_char", "desc": "《王者荣耀》战士，投枪突进、牵马冲锋秀操作", "aliases": ["马超"]},
    {"name": "百里守约", "category": "game_char", "desc": "《王者荣耀》射手，远程狙击、能放视野装置", "aliases": ["百里守约", "守约"]},
    {"name": "镜", "category": "game_char", "desc": "《王者荣耀》刺客，靠镜像分身连招、操作极秀", "aliases": ["jing"]},
    {"name": "澜", "category": "game_char", "desc": "《王者荣耀》刺客，水中突进、适合切后排", "aliases": ["lan"]},
    {"name": "瑶", "category": "game_char", "desc": "《王者荣耀》辅助，能附身队友、套护盾保人", "aliases": ["yao"]},
    {"name": "蔡文姬", "category": "game_char", "desc": "《王者荣耀》辅助，弹琴回血、奶量充足", "aliases": ["蔡文姬"]},
    {"name": "程咬金", "category": "game_char", "desc": "《王者荣耀》坦克，血越少越猛、大招回血", "aliases": ["程咬金"]},
    {"name": "公孙离", "category": "game_char", "desc": "《王者荣耀》射手，靠纸伞位移、风筝输出", "aliases": ["公孙离"]},
    {"name": "上官婉儿", "category": "game_char", "desc": "《王者荣耀》法师，笔墨连招、能超远突进", "aliases": ["上官婉儿", "婉儿"]},
    {"name": "孙悟空", "category": "game_char", "desc": "《王者荣耀》刺客，金箍棒暴击、连跳切后排", "aliases": ["孙悟空", "猴子"]},
    {"name": "王昭君", "category": "game_char", "desc": "《王者荣耀》法师，冰霜控制、大招范围减速", "aliases": ["王昭君"]},
    {"name": "推塔", "category": "game_term", "desc": "打掉防御塔，兵线推进的核心目标", "aliases": ["推塔"]},
    {"name": "红蓝buff", "category": "game_term", "desc": "野区增益野怪，红 buff 加伤害、蓝 buff 减 CD", "aliases": ["红蓝buff", "红buff", "蓝buff"]},
    {"name": "主宰", "category": "game_term", "desc": "王者荣耀的野区大 boss，击杀后给全队增益", "aliases": ["主宰"]},
    {"name": "暴君", "category": "game_term", "desc": "前期野区 boss，击杀获得团队增益", "aliases": ["暴君"]},
    {"name": "打野刀", "category": "game_term", "desc": "打野专用装备，能提升刷野和发育效率", "aliases": ["打野刀"]},
    {"name": "对抗路", "category": "game_term", "desc": "上路的单人对抗线，多为战士坦克", "aliases": ["对抗路"]},
    {"name": "发育路", "category": "game_term", "desc": "下路的双人线，射手在此发育成长", "aliases": ["发育路"]},
    {"name": "游走", "category": "game_term", "desc": "辅助或打野全图跑动支援的定位与打法", "aliases": ["游走"]},
    {"name": "巅峰赛", "category": "game_term", "desc": "高水平玩家参与的排位模式，按分数排名", "aliases": ["巅峰赛"]},
    {"name": "星耀", "category": "game_term", "desc": "排位段位之一，位于钻石与王者之间", "aliases": ["星耀"]},
    {"name": "五排", "category": "game_term", "desc": "五个人凑齐组队开黑打排位的玩法", "aliases": ["五排"]},
    {"name": "铭文", "category": "game_term", "desc": "提升英雄属性的符文系统，需要长期积累", "aliases": ["铭文"]},
    {"name": "KPL", "category": "game_term", "desc": "王者荣耀职业联赛，国内顶级赛事", "aliases": ["kpl"]},
    {"name": "K甲", "category": "game_term", "desc": "王者荣耀职业联赛的次级赛事体系", "aliases": ["k甲"]},

    {"name": "原神", "category": "game", "desc": "米哈游开放世界冒险游戏，以元素反应和七国地图为核心", "aliases": ["原神", "genshin"]},
    {"name": "刻晴", "category": "game_char", "desc": "《原神》璃月七星，雷系单手剑、人气五星角色", "aliases": ["刻晴"]},
    {"name": "钟离", "category": "game_char", "desc": "《原神》岩神，护盾厚、站场能力极强的五星", "aliases": ["钟离"]},
    {"name": "胡桃", "category": "game_char", "desc": "《原神》往生堂主，火系输出、燃烧血量换伤害", "aliases": ["胡桃"]},
    {"name": "雷电将军", "category": "game_char", "desc": "《原神》稻妻雷神，充能快、大招伤害拉满", "aliases": ["雷电将军", "雷神"]},
    {"name": "纳西妲", "category": "game_char", "desc": "《原神》须弥草神，精通反应队的核心辅助", "aliases": ["纳西妲", "草神"]},
    {"name": "元素反应", "category": "game_term", "desc": "用不同元素攻击触发蒸发冻结等额外效果的机制", "aliases": ["元素反应"]},
    {"name": "树脂", "category": "game_term", "desc": "原神的体力值，刷副本和领奖励都要消耗", "aliases": ["树脂"]},

    {"name": "星穹铁道", "category": "game", "desc": "米哈游回合制 RPG，简称崩铁或星铁", "aliases": ["星穹铁道", "崩铁", "星铁"]},
    {"name": "卡芙卡", "category": "game_char", "desc": "《星穹铁道》星核猎手，持续伤害队的核心", "aliases": ["卡芙卡"]},
    {"name": "银狼", "category": "game_char", "desc": "《星穹铁道》星核猎手，能扒敌人弱点、挂减益", "aliases": ["银狼"]},
    {"name": "景元", "category": "game_char", "desc": "《星穹铁道》罗浮将军，靠神君追击输出", "aliases": ["景元"]},
    {"name": "花火", "category": "game_char", "desc": "《星穹铁道》同谐角色，能拉行动条、加暴伤", "aliases": ["花火"]},
    {"name": "流萤", "category": "game_char", "desc": "《星穹铁道》巡猎角色，机甲形态、能自爆打工", "aliases": ["流萤"]},
    {"name": "命途", "category": "game_term", "desc": "星铁里角色的职业定位分类，如存护巡猎等", "aliases": ["命途"]},
    {"name": "光锥", "category": "game_term", "desc": "星铁里的武器系统，相当于角色的装备", "aliases": ["光锥"]},
    {"name": "遗器", "category": "game_term", "desc": "星铁的角色装备，靠刷副本凑套装词条", "aliases": ["遗器"]},

    {"name": "绝区零", "category": "game", "desc": "米哈游都市动作游戏，主打高速连招战斗", "aliases": ["绝区零", "zzz"]},
    {"name": "安比", "category": "game_char", "desc": "《绝区零》狡兔屋成员，电系双刀、手感极佳", "aliases": ["安比"]},
    {"name": "妮可", "category": "game_char", "desc": "《绝区零》狡兔屋社长，能开黑洞聚怪", "aliases": ["妮可"]},
    {"name": "星见雅", "category": "game_char", "desc": "《绝区零》虚狩之一，冰系太刀、人气极高", "aliases": ["星见雅"]},
    {"name": "空洞", "category": "game_term", "desc": "绝区零里的探索副本区域，有随机事件与奖励", "aliases": ["空洞"]},

    {"name": "反恐精英", "category": "game", "desc": "经典战术射击游戏，指 CS2 或 CSGO", "aliases": ["cs2", "csgo", "反恐精英"]},
    {"name": "沙二", "category": "game_term", "desc": "CS 经典地图 Dust2 的俗称，中路对狙名场面多", "aliases": ["沙二", "dust2"]},
    {"name": "沙鹰", "category": "game_term", "desc": "CS 里的高伤害手枪，爆头一枪一个、性价比高", "aliases": ["沙鹰", "沙漠之鹰"]},
    {"name": "AWP", "category": "game_term", "desc": "CS 里的经典狙击枪，一枪毙命、走位灵活", "aliases": ["awp"]},
    {"name": "磨损", "category": "game_term", "desc": "CS 皮肤的磨损度，决定外观新旧和价格高低", "aliases": ["磨损"]},

    {"name": "DOTA2", "category": "game", "desc": "V 社 MOBA 端游，赛事最高为 TI 国际邀请赛", "aliases": ["dota2", "dota"]},
    {"name": "影魔", "category": "game_char", "desc": "《DOTA2》中路刺客，攒灵魂叠攻击、操作上限高", "aliases": ["影魔", "sf"]},
    {"name": "敌法师", "category": "game_char", "desc": "《DOTA2》后期核心，削蓝加跳刀、能牵制带线", "aliases": ["敌法师"]},
    {"name": "屠夫", "category": "game_char", "desc": "《DOTA2》帕吉，钩子加咬人秒杀、人气极高", "aliases": ["屠夫", "帕吉"]},
    {"name": "反补", "category": "game_term", "desc": "打死自家残血小兵，让对手吃不到经验和金币", "aliases": ["反补"]},
    {"name": "TI", "category": "game_term", "desc": "DOTA2 国际邀请赛，奖金池常年全球第一", "aliases": ["ti", "国际邀请赛"]},

    {"name": "永劫无间", "category": "game", "desc": "国产武侠吃鸡类动作游戏，主打拼刀与冷兵器对战", "aliases": ["永劫无间", "永劫"]},
    {"name": "振刀", "category": "game_term", "desc": "格挡后反击的核心机制，会玩就能反打", "aliases": ["振刀"]},
    {"name": "拼刀", "category": "game_term", "desc": "双方近身对拼、比拼攻击判定的博弈", "aliases": ["拼刀"]},
    {"name": "宁红夜", "category": "game_char", "desc": "《永劫无间》人气女角色，双刀刺客、身法飘逸", "aliases": ["宁红夜"]},
    {"name": "迦南", "category": "game_char", "desc": "《永劫无间》机动型角色，能瞬移偷袭", "aliases": ["迦南"]},
    {"name": "魂玉", "category": "game_term", "desc": "永劫无间里的强化道具，装上能改技能与属性", "aliases": ["魂玉"]},

    {"name": "我的世界", "category": "game", "desc": "沙盒建造游戏，玩家常聊红石、模组与生存", "aliases": ["我的世界", "minecraft", "mc"]},
    {"name": "红石", "category": "game_term", "desc": "我的世界里的电路系统，能造自动机械", "aliases": ["红石"]},
    {"name": "苦力怕", "category": "game_term", "desc": "会自爆的绿色怪物，靠近就炸、阴人一把手", "aliases": ["苦力怕", "creeper"]},
    {"name": "末影龙", "category": "game_term", "desc": "我的世界的最终 boss，打完通关末地", "aliases": ["末影龙"]},
    {"name": "附魔", "category": "game_term", "desc": "给装备加属性的强化方式，需要经验与青金石", "aliases": ["附魔"]},

    {"name": "第五人格", "category": "game", "desc": "网易 1v4 非对称对抗游戏，俗称屠夫与求生者", "aliases": ["第五人格"]},
    {"name": "求生者", "category": "game_term", "desc": "第五人格里负责破译逃生的四人阵营", "aliases": ["求生者"]},
    {"name": "监管者", "category": "game_term", "desc": "第五人格里负责抓人的单人阵营，俗称屠夫", "aliases": ["监管者"]},
    {"name": "破译", "category": "game_term", "desc": "求生者解密码机的主要任务与得分方式", "aliases": ["破译"]},
    {"name": "杰克", "category": "game_char", "desc": "《第五人格》经典监管者，雾刃与雾区是招牌", "aliases": ["杰克"]},
    {"name": "红蝶", "category": "game_char", "desc": "《第五人格》监管者，能化蝶位移追击求生者", "aliases": ["红蝶"]},

    {"name": "金铲铲之战", "category": "game", "desc": "腾讯自走棋手游，对应端游云顶之弈", "aliases": ["金铲铲", "云顶之弈"]},
    {"name": "羁绊", "category": "game_term", "desc": "自走棋里凑齐同类别棋子获得的加成效果", "aliases": ["羁绊"]},
    {"name": "海克斯", "category": "game_term", "desc": "开局选择的强化天赋，决定阵容走向", "aliases": ["海克斯"]},
    {"name": "五费卡", "category": "game_term", "desc": "最贵的五费棋子，抽到往往就是阵容核心", "aliases": ["五费卡"]},
    {"name": "拉人口", "category": "game_term", "desc": "花钱买经验提升等级，好多上一个棋子", "aliases": ["拉人口"]},

    {"name": "黑神话：悟空", "category": "game", "desc": "2024 年国产单机动作游戏，以西游为题材", "aliases": ["黑神话", "黑猴", "悟空"]},
    {"name": "棍法", "category": "game_term", "desc": "黑神话的三种棍势切换，劈棍立棍戳棍各有妙用", "aliases": ["棍法", "棍势"]},
    {"name": "定身术", "category": "game_term", "desc": "黑神话的法术，定住敌人后可以尽情输出", "aliases": ["定身术"]},
    {"name": "二郎神", "category": "game_char", "desc": "《黑神话：悟空》终极 boss，三尖两刃刀、难度极高", "aliases": ["二郎神"]},

    {"name": "和平精英", "category": "game", "desc": "腾讯战术竞技手游，玩家俗称吃鸡", "aliases": ["和平精英", "吃鸡", "pubg"]},
    {"name": "决赛圈", "category": "game_term", "desc": "缩圈到最后的小范围，剩最后几队决战", "aliases": ["决赛圈"]},
    {"name": "空投", "category": "game_term", "desc": "飞机扔下的补给箱，里面有高级装备", "aliases": ["空投"]},
    {"name": "三级头", "category": "game_term", "desc": "最高级头盔，能挡不少伤害的保命装备", "aliases": ["三级头"]},
    {"name": "缩圈", "category": "game_term", "desc": "安全区不断缩小，逼着玩家向中心靠拢", "aliases": ["缩圈", "安全区"]},
    {"name": "钢枪", "category": "game_term", "desc": "正面硬碰硬对枪，比谁的反应和枪法更好", "aliases": ["钢枪"]},

    {"name": "蛋仔派对", "category": "game", "desc": "网易休闲派对游戏，画风可爱、地图多样", "aliases": ["蛋仔派对", "蛋仔"]},
    {"name": "滚动", "category": "game_term", "desc": "蛋仔的招牌动作，滚起来速度快还能撞人", "aliases": ["滚动"]},
    {"name": "派对季", "category": "game_term", "desc": "蛋仔的赛季玩法，每个赛季主题和奖励不同", "aliases": ["派对季"]},

    {"name": "逃离塔科夫", "category": "game", "desc": "硬核撤离类射击游戏，俗称塔科夫", "aliases": ["逃离塔科夫", "塔科夫"]},
    {"name": "跳蚤市场", "category": "game_term", "desc": "塔科夫里的玩家交易市场，可自由买卖物资", "aliases": ["跳蚤市场"]},
    {"name": "钥匙卡", "category": "game_term", "desc": "塔科夫里打开高价值房间的门禁卡", "aliases": ["钥匙卡"]},

    {"name": "幻兽帕鲁", "category": "game", "desc": "2024 年爆火的抓宠生存建造游戏", "aliases": ["幻兽帕鲁", "帕鲁"]},
    {"name": "配种", "category": "game_term", "desc": "让两只帕鲁繁殖，孵出更强或更稀有的新帕鲁", "aliases": ["配种"]},
    {"name": "塔主", "category": "game_term", "desc": "地图塔顶的 boss 首领，打完解锁传送点", "aliases": ["塔主"]},

    {"name": "鸣潮", "category": "game", "desc": "库洛开放世界动作游戏，常与原神对比", "aliases": ["鸣潮"]},
    {"name": "忌炎", "category": "game_char", "desc": "《鸣潮》五星角色，长枪输出、是开服人气担当", "aliases": ["忌炎"]},
    {"name": "长离", "category": "game_char", "desc": "《鸣潮》五星角色，火系、输出与辅助兼具", "aliases": ["长离"]},
    {"name": "守岸人", "category": "game_char", "desc": "《鸣潮》五星辅助，能大幅提升队伍伤害", "aliases": ["守岸人"]},
    {"name": "声骸", "category": "game_term", "desc": "鸣潮的装备系统，击败怪物获得并加以强化", "aliases": ["声骸"]},

    {"name": "明日方舟", "category": "game", "desc": "鹰角塔防养成手游，衍生作有终末地", "aliases": ["明日方舟", "方舟"]},
    {"name": "阿米娅", "category": "game_char", "desc": "《明日方舟》看板娘，罗德岛领袖、剧情核心", "aliases": ["阿米娅"]},
    {"name": "能天使", "category": "game_char", "desc": "《明日方舟》人气狙击干员，早期开荒神器", "aliases": ["能天使"]},
    {"name": "银灰", "category": "game_char", "desc": "《明日方舟》喀兰贸易老板，人气六星近卫", "aliases": ["银灰"]},
    {"name": "干员", "category": "game_term", "desc": "明日方舟里可部署的作战单位统称", "aliases": ["干员"]},
    {"name": "源石", "category": "game_term", "desc": "明日方舟的核心设定与货币，抽卡强化都要它", "aliases": ["源石"]},
    {"name": "精二", "category": "game_term", "desc": "干员精英化第二阶段，大幅提升强度", "aliases": ["精二", "精英化"]},
    {"name": "危机合约", "category": "game_term", "desc": "明日方舟的高难挑战玩法，玩家自选难度词条", "aliases": ["危机合约"]},
]
