"""热门生活词库：地名旅游、兴趣爱好与音乐，供弹幕高亮与归类使用。"""

TOPICS = [
    # ---------------------------------------------------------- 旅游：国内地名
    {"name": "云南", "category": "travel", "desc": "西南旅游大省，大理、丽江、香格里拉都在这里", "aliases": ["云南"]},
    {"name": "大理", "category": "travel", "desc": "云南城市，苍山洱海与风花雪月是它的代名词", "aliases": ["大理"]},
    {"name": "丽江", "category": "travel", "desc": "云南古城，玉龙雪山与束河古镇是必去景点", "aliases": ["丽江"]},
    {"name": "香格里拉", "category": "travel", "desc": "云南藏区城市，普达措与松赞林寺所在地", "aliases": ["香格里拉"]},
    {"name": "西安", "category": "travel", "desc": "陕西古都，兵马俑、城墙与回民街美食之城", "aliases": ["西安"]},
    {"name": "成都", "category": "travel", "desc": "四川省会，熊猫基地与火锅串串遍地都是", "aliases": ["成都"]},
    {"name": "重庆", "category": "travel", "desc": "山城雾都，洪崖洞夜景与火锅的代表城市", "aliases": ["重庆"]},
    {"name": "长沙", "category": "travel", "desc": "湖南省会，茶颜悦色与夜宵文化很出名", "aliases": ["长沙"]},
    {"name": "三亚", "category": "travel", "desc": "海南海滨城市，亚龙湾与天涯海角所在地", "aliases": ["三亚"]},
    {"name": "海南", "category": "travel", "desc": "南方海岛省份，三亚海口与免税购物胜地", "aliases": ["海南"]},
    {"name": "哈尔滨", "category": "travel", "desc": "黑龙江省会，冰雪大世界与中央大街必逛", "aliases": ["哈尔滨", "冰城"]},
    {"name": "漠河", "category": "travel", "desc": "中国最北的城市，可以看极光与北极村", "aliases": ["漠河"]},
    {"name": "淄博", "category": "travel", "desc": "山东城市，因烧烤在网络上爆火成为旅游热点", "aliases": ["淄博"]},
    {"name": "天水", "category": "travel", "desc": "甘肃城市，因一碗麻辣烫在网上出圈走红", "aliases": ["天水"]},
    {"name": "新疆", "category": "travel", "desc": "西北自治区，喀纳斯与独库公路是自驾天堂", "aliases": ["新疆"]},
    {"name": "喀什", "category": "travel", "desc": "新疆城市，老城与帕米尔风情的西域门户", "aliases": ["喀什"]},
    {"name": "伊犁", "category": "travel", "desc": "新疆地区，那拉提草原与薰衣草花海著名", "aliases": ["伊犁"]},
    {"name": "西藏", "category": "travel", "desc": "高原自治区，布达拉宫与雪山圣湖遍布", "aliases": ["西藏"]},
    {"name": "拉萨", "category": "travel", "desc": "西藏首府，布达拉宫与八廓街都在这里", "aliases": ["拉萨"]},
    {"name": "林芝", "category": "travel", "desc": "西藏地区，桃花与南迦巴瓦峰是标志景观", "aliases": ["林芝"]},
    {"name": "婺源", "category": "travel", "desc": "江西乡村，油菜花与徽派古村落代表地", "aliases": ["婺源"]},
    {"name": "张家界", "category": "travel", "desc": "湖南景区，奇峰石柱与玻璃栈道非常出名", "aliases": ["张家界"]},
    {"name": "黄山", "category": "travel", "desc": "安徽名山，云海奇松怪石与迎客松最出名", "aliases": ["黄山"]},
    {"name": "敦煌", "category": "travel", "desc": "甘肃城市，莫高窟与鸣沙山月牙泉所在地", "aliases": ["敦煌", "莫高窟"]},
    {"name": "青海湖", "category": "travel", "desc": "青海最大的湖泊，环湖骑行与油菜花海", "aliases": ["青海湖"]},
    {"name": "茶卡盐湖", "category": "travel", "desc": "青海盐湖，被称为天空之镜的著名拍照地", "aliases": ["茶卡盐湖", "茶卡"]},
    {"name": "甘南", "category": "travel", "desc": "甘肃南部藏区，草原风光与拉卜楞寺所在", "aliases": ["甘南"]},
    {"name": "内蒙古", "category": "travel", "desc": "北方自治区，草原与沙漠风光的旅游目的地", "aliases": ["内蒙古", "内蒙"]},
    {"name": "呼伦贝尔", "category": "travel", "desc": "内蒙古草原，夏季避暑与牧场风光出名", "aliases": ["呼伦贝尔"]},
    {"name": "延吉", "category": "travel", "desc": "吉林城市，朝鲜族美食与网红打卡地", "aliases": ["延吉"]},
    {"name": "厦门", "category": "travel", "desc": "福建海滨城市，鼓浪屿与环岛路都很出名", "aliases": ["厦门", "鼓浪屿"]},
    {"name": "青岛", "category": "travel", "desc": "山东海滨城市，栈桥与啤酒节是代表地", "aliases": ["青岛"]},
    {"name": "大连", "category": "travel", "desc": "辽宁海滨城市，星海广场与老虎滩著名", "aliases": ["大连"]},
    {"name": "苏州", "category": "travel", "desc": "江苏城市，园林与平江路代表江南水乡", "aliases": ["苏州", "姑苏"]},
    {"name": "杭州", "category": "travel", "desc": "浙江省会，西湖与灵隐寺代表江南风光", "aliases": ["杭州", "西湖"]},
    {"name": "南京", "category": "travel", "desc": "江苏古都，夫子庙与梧桐大道都在这里", "aliases": ["南京", "金陵"]},
    {"name": "洛阳", "category": "travel", "desc": "河南古都，龙门石窟与牡丹花会出名", "aliases": ["洛阳"]},
    {"name": "开封", "category": "travel", "desc": "河南古都，清明上河园与夜市小吃闻名", "aliases": ["开封"]},
    {"name": "平遥", "category": "travel", "desc": "山西古城，完整保存的明清县城风貌", "aliases": ["平遥", "平遥古城"]},
    {"name": "凤凰古城", "category": "travel", "desc": "湖南古城，沱江吊脚楼与沈从文故乡", "aliases": ["凤凰古城"]},
    {"name": "西双版纳", "category": "travel", "desc": "云南热带地区，泼水节与热带雨林著名", "aliases": ["西双版纳", "版纳"]},
    {"name": "桂林", "category": "travel", "desc": "广西城市，漓江山水甲天下是它的招牌", "aliases": ["桂林", "阳朔"]},
    {"name": "稻城亚丁", "category": "travel", "desc": "四川景区，雪山海子被称为最后的香格里拉", "aliases": ["稻城亚丁", "亚丁", "稻城"]},
    {"name": "四姑娘山", "category": "travel", "desc": "四川雪山，徒步与登山爱好者的胜地", "aliases": ["四姑娘山"]},
    {"name": "武功山", "category": "travel", "desc": "江西高山草甸，露营看云海的热门徒步地", "aliases": ["武功山"]},
    {"name": "泰山", "category": "travel", "desc": "山东五岳之首，登顶看日出是经典玩法", "aliases": ["泰山", "爬泰山"]},
    {"name": "华山", "category": "travel", "desc": "陕西五岳之一，以险峻的长空栈道出名", "aliases": ["华山"]},
    {"name": "峨眉山", "category": "travel", "desc": "四川佛教名山，金顶云海与猴子很出名", "aliases": ["峨眉山", "峨眉"]},
    {"name": "莫干山", "category": "travel", "desc": "浙江避暑名山，民宿与竹林度假的好去处", "aliases": ["莫干山"]},
    {"name": "阿那亚", "category": "travel", "desc": "河北海边社区，孤独图书馆与礼堂打卡地", "aliases": ["阿那亚"]},
    {"name": "崇礼", "category": "travel", "desc": "河北滑雪胜地，冬奥会雪上项目举办地", "aliases": ["崇礼"]},
    {"name": "北戴河", "category": "travel", "desc": "河北海滨，夏季避暑与看海的老牌目的地", "aliases": ["北戴河"]},

    # ---------------------------------------------------------- 旅游：国外目的地
    {"name": "日本", "category": "travel", "desc": "东亚岛国，樱花温泉与动漫文化都很出名", "aliases": ["日本"]},
    {"name": "东京", "category": "travel", "desc": "日本首都，涩谷秋叶原与购物美食之都", "aliases": ["东京", "tokyo"]},
    {"name": "大阪", "category": "travel", "desc": "日本城市，道顿堀美食与环球影城所在", "aliases": ["大阪", "osaka"]},
    {"name": "京都", "category": "travel", "desc": "日本古都，清水寺与千本鸟居都在这里", "aliases": ["京都", "kyoto"]},
    {"name": "北海道", "category": "travel", "desc": "日本北部地区，滑雪与薰衣草花田胜地", "aliases": ["北海道", "hokkaido"]},
    {"name": "冲绳", "category": "travel", "desc": "日本海岛县，拥有沙滩海景与琉球文化", "aliases": ["冲绳", "okinawa"]},
    {"name": "韩国", "category": "travel", "desc": "东亚国家，首尔明洞与济州岛旅游热门", "aliases": ["韩国"]},
    {"name": "首尔", "category": "travel", "desc": "韩国首都，明洞弘大与景福宫都在这里", "aliases": ["首尔", "seoul"]},
    {"name": "济州岛", "category": "travel", "desc": "韩国海岛，汉拿山与海岸风光很有名", "aliases": ["济州岛", "济州"]},
    {"name": "泰国", "category": "travel", "desc": "东南亚国家，海岛与寺庙是旅游热门", "aliases": ["泰国"]},
    {"name": "曼谷", "category": "travel", "desc": "泰国首都，大皇宫与夜市美食闻名的城市", "aliases": ["曼谷", "bangkok"]},
    {"name": "清迈", "category": "travel", "desc": "泰国北部城市，古城与文艺慢生活出名", "aliases": ["清迈", "chiangmai"]},
    {"name": "普吉岛", "category": "travel", "desc": "泰国最大海岛，沙滩与潜水度假胜地", "aliases": ["普吉岛", "普吉"]},
    {"name": "巴厘岛", "category": "travel", "desc": "印尼著名海岛，海滩与网红悬崖秋千", "aliases": ["巴厘岛", "巴厘"]},
    {"name": "新加坡", "category": "travel", "desc": "东南亚城市国家，花园城市与环球影城", "aliases": ["新加坡", "狮城"]},
    {"name": "马来西亚", "category": "travel", "desc": "东南亚国家，吉隆坡与仙本那海岛著名", "aliases": ["马来西亚", "大马"]},
    {"name": "越南", "category": "travel", "desc": "东南亚国家，岘港与芽庄海滨旅游热门", "aliases": ["越南"]},
    {"name": "岘港", "category": "travel", "desc": "越南海滨城市，美溪沙滩与巴拿山出名", "aliases": ["岘港"]},
    {"name": "迪拜", "category": "travel", "desc": "阿联酋城市，哈利法塔与沙漠奢华旅游", "aliases": ["迪拜", "dubai"]},
    {"name": "土耳其", "category": "travel", "desc": "横跨欧亚的国家，热气球与清真寺闻名", "aliases": ["土耳其"]},
    {"name": "卡帕多奇亚", "category": "travel", "desc": "土耳其中部地区，热气球与奇岩地貌", "aliases": ["卡帕多奇亚"]},
    {"name": "埃及", "category": "travel", "desc": "北非国家，金字塔与尼罗河古文明闻名", "aliases": ["埃及"]},
    {"name": "冰岛", "category": "travel", "desc": "北欧岛国，极光与蓝湖温泉非常出名", "aliases": ["冰岛"]},
    {"name": "挪威", "category": "travel", "desc": "北欧国家，峡湾风光与极光旅游胜地", "aliases": ["挪威"]},
    {"name": "瑞士", "category": "travel", "desc": "中欧国家，雪山湖泊与少女峰的风光", "aliases": ["瑞士"]},
    {"name": "巴黎", "category": "travel", "desc": "法国首都，埃菲尔铁塔与卢浮宫著名", "aliases": ["巴黎", "paris"]},
    {"name": "伦敦", "category": "travel", "desc": "英国首都，大本钟与泰晤士河著名景点", "aliases": ["伦敦", "london"]},
    {"name": "罗马", "category": "travel", "desc": "意大利首都，斗兽场与古罗马遗迹众多", "aliases": ["罗马", "rome"]},
    {"name": "威尼斯", "category": "travel", "desc": "意大利水城，以贡多拉与圣马可广场闻名", "aliases": ["威尼斯", "venice"]},
    {"name": "圣托里尼", "category": "travel", "desc": "希腊海岛，以蓝白房子与爱琴海日落闻名", "aliases": ["圣托里尼", "santorini"]},
    {"name": "马尔代夫", "category": "travel", "desc": "印度洋岛国，蜜月与水上屋度假胜地", "aliases": ["马尔代夫", "马代"]},
    {"name": "新西兰", "category": "travel", "desc": "大洋洲国家，中土世界与自然风光出名", "aliases": ["新西兰"]},
    {"name": "澳洲", "category": "travel", "desc": "大洋洲国家，悉尼歌剧院与袋鼠考拉", "aliases": ["澳洲", "澳大利亚"]},
    {"name": "洛杉矶", "category": "travel", "desc": "美国西海岸城市，好莱坞与环球影城", "aliases": ["洛杉矶", "los angeles"]},
    {"name": "纽约", "category": "travel", "desc": "美国东海岸城市，自由女神与时代广场", "aliases": ["纽约", "new york"]},
    {"name": "拉斯维加斯", "category": "travel", "desc": "美国沙漠城市，赌场与大型秀场之都", "aliases": ["拉斯维加斯", "vegas"]},

    # ---------------------------------------------------------- 旅游：方式与相关词
    {"name": "穷游", "category": "travel", "desc": "花最少的钱去更多地方的旅行方式", "aliases": ["穷游"]},
    {"name": "自由行", "category": "travel", "desc": "不跟团旅游、自己规划行程的旅行方式", "aliases": ["自由行"]},
    {"name": "自驾", "category": "travel", "desc": "自己开车上路的出行方式，也叫自驾游", "aliases": ["自驾", "自驾游"]},
    {"name": "房车", "category": "travel", "desc": "开着房车边行驶边住宿的旅行方式", "aliases": ["房车"]},
    {"name": "徒步", "category": "travel", "desc": "靠双脚长距离行走的户外旅行方式", "aliases": ["徒步"]},
    {"name": "citywalk", "category": "travel", "desc": "在城市里漫无目的边逛边走的轻旅行", "aliases": ["citywalk"]},
    {"name": "特种兵旅游", "category": "travel", "desc": "用极短时间高强度打卡多个景点的玩法", "aliases": ["特种兵旅游", "特种兵式旅游"]},

    # ---------------------------------------------------------- 兴趣：运动健身
    {"name": "健身", "category": "hobby", "desc": "到健身房锻炼增肌塑形的运动方式", "aliases": ["健身"]},
    {"name": "撸铁", "category": "hobby", "desc": "举铁练力量的健身说法，指力量训练", "aliases": ["撸铁"]},
    {"name": "跑步", "category": "hobby", "desc": "日常慢跑锻炼身体，也指打卡式的跑步", "aliases": ["跑步"]},
    {"name": "马拉松", "category": "hobby", "desc": "长距离公路长跑比赛，全程四十多公里", "aliases": ["马拉松"]},
    {"name": "骑行", "category": "hobby", "desc": "骑自行车长途旅行或休闲锻炼的运动", "aliases": ["骑行"]},
    {"name": "游泳", "category": "hobby", "desc": "在水中游泳锻炼的全身性运动项目", "aliases": ["游泳"]},
    {"name": "羽毛球", "category": "hobby", "desc": "两人或四人对打、隔着球网进行的运动", "aliases": ["羽毛球"]},
    {"name": "乒乓球", "category": "hobby", "desc": "被称为国球，两人隔桌对打的球类运动", "aliases": ["乒乓球"]},
    {"name": "篮球", "category": "hobby", "desc": "五人对抗的球类运动，投篮进筐得分", "aliases": ["篮球"]},
    {"name": "足球", "category": "hobby", "desc": "世界第一运动，双方各十一人上场的对抗", "aliases": ["足球"]},
    {"name": "台球", "category": "hobby", "desc": "用球杆击球入袋的桌球类室内运动", "aliases": ["台球"]},
    {"name": "网球", "category": "hobby", "desc": "隔着球网并用球拍对打的运动项目", "aliases": ["网球"]},
    {"name": "滑雪", "category": "hobby", "desc": "踩着雪板在雪道上滑行的冬季运动", "aliases": ["滑雪"]},
    {"name": "滑板", "category": "hobby", "desc": "踩着滑板做各种技巧动作的街头运动", "aliases": ["滑板"]},
    {"name": "攀岩", "category": "hobby", "desc": "借助岩点向上攀爬的极限运动项目", "aliases": ["攀岩"]},
    {"name": "拳击", "category": "hobby", "desc": "戴着拳套在擂台上对打的格斗运动", "aliases": ["拳击"]},
    {"name": "瑜伽", "category": "hobby", "desc": "注重呼吸与柔韧性的健身运动方式", "aliases": ["瑜伽"]},
    {"name": "飞盘", "category": "hobby", "desc": "近年流行起来的团队投掷类户外运动", "aliases": ["飞盘"]},

    # ---------------------------------------------------------- 兴趣：数码游戏外设
    {"name": "装机", "category": "hobby", "desc": "自己组装台式电脑，讨论配置与走线", "aliases": ["装机"]},
    {"name": "显卡", "category": "hobby", "desc": "电脑的图形处理器，装机时的核心配件", "aliases": ["显卡"]},
    {"name": "机械键盘", "category": "hobby", "desc": "手感清脆的键盘，常聊轴体与客制化", "aliases": ["机械键盘", "客制化键盘"]},
    {"name": "耳机", "category": "hobby", "desc": "听歌打游戏用的音频设备，讲究音质", "aliases": ["耳机"]},
    {"name": "hifi", "category": "hobby", "desc": "高保真音质，发烧友追求的声音品质", "aliases": ["hifi"]},
    {"name": "相机", "category": "hobby", "desc": "拍照用的设备，讨论镜头、机身与画质", "aliases": ["相机"]},
    {"name": "微单", "category": "hobby", "desc": "可以更换镜头的无反相机，轻便好用", "aliases": ["微单"]},
    {"name": "索尼", "category": "hobby", "desc": "日本电子品牌，相机耳机游戏机都有", "aliases": ["索尼", "sony"]},
    {"name": "富士", "category": "hobby", "desc": "日本相机品牌，胶片模拟色彩很出名", "aliases": ["富士"]},
    {"name": "无人机", "category": "hobby", "desc": "航拍用的无人飞行器，常拍风景大片", "aliases": ["无人机"]},
    {"name": "掌机", "category": "hobby", "desc": "便携式的游戏机，可以随身携带游玩", "aliases": ["掌机"]},
    {"name": "switch", "category": "hobby", "desc": "任天堂推出的掌机主机一体游戏机", "aliases": ["switch"]},
    {"name": "ps5", "category": "hobby", "desc": "索尼推出的次世代家用游戏主机产品", "aliases": ["ps5"]},
    {"name": "steam deck", "category": "hobby", "desc": "可以运行电脑游戏的掌上游戏机设备", "aliases": ["steam deck"]},
    {"name": "外设", "category": "hobby", "desc": "键盘鼠标等电脑周边外接设备的统称", "aliases": ["外设"]},
    {"name": "鼠标", "category": "hobby", "desc": "电脑指点设备，选购时常聊 DPI 与握持手感", "aliases": ["鼠标"]},
    {"name": "显示器", "category": "hobby", "desc": "电脑屏幕，选购时讨论刷新率与分辨率", "aliases": ["显示器"]},
    {"name": "电竞椅", "category": "hobby", "desc": "主打人体工学设计的电竞游戏座椅", "aliases": ["电竞椅"]},

    # ---------------------------------------------------------- 兴趣：生活爱好
    {"name": "摄影", "category": "hobby", "desc": "用相机记录画面，讲究构图与光影运用", "aliases": ["摄影"]},
    {"name": "vlog", "category": "hobby", "desc": "记录日常生活的视频形式，常拍常更", "aliases": ["vlog"]},
    {"name": "剪辑", "category": "hobby", "desc": "把拍好的素材拼接成片的后期工作", "aliases": ["剪辑"]},
    {"name": "绘画", "category": "hobby", "desc": "画画，包含手绘与板绘等不同的形式", "aliases": ["绘画", "板绘"]},
    {"name": "书法", "category": "hobby", "desc": "用毛笔或硬笔写字的传统艺术爱好", "aliases": ["书法"]},
    {"name": "手办", "category": "hobby", "desc": "动漫角色的立体模型摆件，俗称手办", "aliases": ["手办"]},
    {"name": "拼装模型", "category": "hobby", "desc": "自己动手拼装的高达等模型类玩具", "aliases": ["拼装模型", "高达模型"]},
    {"name": "乐高", "category": "hobby", "desc": "丹麦积木玩具，可以拼搭出各种造型", "aliases": ["乐高", "积木"]},
    {"name": "穿搭", "category": "hobby", "desc": "研究衣服搭配与塑造个人风格的爱好", "aliases": ["穿搭"]},
    {"name": "美妆", "category": "hobby", "desc": "化妆以及分享彩妆产品的兴趣爱好", "aliases": ["美妆"]},
    {"name": "护肤", "category": "hobby", "desc": "保养皮肤并研究护肤品成分的过程", "aliases": ["护肤"]},
    {"name": "香水", "category": "hobby", "desc": "研究香调与香水品牌的小众兴趣爱好", "aliases": ["香水"]},
    {"name": "汉服", "category": "hobby", "desc": "汉族传统服饰，常搭配妆造出门拍照", "aliases": ["汉服"]},
    {"name": "jk", "category": "hobby", "desc": "模仿日式女高中生制服的穿搭风格", "aliases": ["jk"]},
    {"name": "lolita", "category": "hobby", "desc": "以华丽蓬裙为主的洛丽塔服饰风格", "aliases": ["lolita"]},
    {"name": "cosplay", "category": "hobby", "desc": "扮演动漫或游戏角色的装扮与表演", "aliases": ["cosplay", "cos"]},
    {"name": "纹身", "category": "hobby", "desc": "在皮肤上刺纹图案的身体艺术爱好", "aliases": ["纹身"]},
    {"name": "养猫", "category": "hobby", "desc": "在家里养猫，也指撸猫的日常生活方式", "aliases": ["养猫", "撸猫"]},
    {"name": "养狗", "category": "hobby", "desc": "在家里养狗，经常分享遛狗的日常生活", "aliases": ["养狗"]},
    {"name": "多肉", "category": "hobby", "desc": "养护叶片肥厚的多肉植物的日常爱好", "aliases": ["多肉"]},
    {"name": "绿植", "category": "hobby", "desc": "在家里养护观叶植物的休闲类爱好", "aliases": ["绿植"]},
    {"name": "养鱼", "category": "hobby", "desc": "饲养观赏鱼并且布置水族箱的爱好", "aliases": ["养鱼"]},
    {"name": "钓鱼", "category": "hobby", "desc": "在河边或鱼塘垂钓的休闲户外爱好", "aliases": ["钓鱼"]},
    {"name": "下厨", "category": "hobby", "desc": "自己动手做饭做菜的日常小兴趣爱好", "aliases": ["下厨"]},
    {"name": "烘焙", "category": "hobby", "desc": "烤制蛋糕、面包等甜点的厨房类爱好", "aliases": ["烘焙"]},
    {"name": "咖啡", "category": "hobby", "desc": "研究咖啡豆与冲煮方式的饮品爱好", "aliases": ["咖啡", "手冲"]},
    {"name": "奶茶", "category": "hobby", "desc": "加奶加料的茶饮，是年轻人的续命水", "aliases": ["奶茶"]},
    {"name": "火锅", "category": "hobby", "desc": "边煮边吃的聚餐方式，以川渝最为出名", "aliases": ["火锅"]},
    {"name": "烧烤", "category": "hobby", "desc": "炭火烤串配啤酒的夜宵聚餐类爱好", "aliases": ["烧烤"]},
    {"name": "日料", "category": "hobby", "desc": "寿司、刺身等日本料理的统称类词语", "aliases": ["日料"]},
    {"name": "探店", "category": "hobby", "desc": "专门去店里实地试吃并打卡的分享", "aliases": ["探店"]},
    {"name": "剧本杀", "category": "hobby", "desc": "按剧本扮演角色、推理破案的聚会游戏", "aliases": ["剧本杀"]},
    {"name": "狼人杀", "category": "hobby", "desc": "靠发言与投票找出狼人的语言游戏", "aliases": ["狼人杀"]},
    {"name": "桌游", "category": "hobby", "desc": "桌面上的各类纸牌与棋类游戏统称", "aliases": ["桌游"]},
    {"name": "麻将", "category": "hobby", "desc": "四人围坐对局的国粹棋牌类桌面游戏", "aliases": ["麻将"]},
    {"name": "象棋", "category": "hobby", "desc": "中国象棋，隔着楚河汉界对弈的棋类游戏", "aliases": ["象棋"]},
    {"name": "盲盒", "category": "hobby", "desc": "购买之前不知道款式的小摆件玩法", "aliases": ["盲盒"]},
    {"name": "谷子", "category": "hobby", "desc": "动漫周边商品，徽章、立牌等物品的俗称", "aliases": ["谷子"]},
    {"name": "露营", "category": "hobby", "desc": "在户外搭帐篷过夜的休闲方式，讲究装备", "aliases": ["露营"]},

    # ---------------------------------------------------------- 音乐：华语歌手
    {"name": "周杰伦", "category": "music", "desc": "华语流行乐坛天王，代表作《晴天》《稻香》", "aliases": ["周杰伦", "杰伦"]},
    {"name": "林俊杰", "category": "music", "desc": "新加坡华语男歌手，代表作《江南》《曹操》", "aliases": ["林俊杰", "jj"]},
    {"name": "陈奕迅", "category": "music", "desc": "香港男歌手，代表作《十年》《浮夸》《孤勇者》", "aliases": ["陈奕迅", "eason"]},
    {"name": "邓紫棋", "category": "music", "desc": "香港创作女歌手，代表作《光年之外》《泡沫》", "aliases": ["邓紫棋", "gem"]},
    {"name": "薛之谦", "category": "music", "desc": "内地歌手，代表作《演员》《丑八怪》《认真的雪》", "aliases": ["薛之谦"]},
    {"name": "五月天", "category": "music", "desc": "台湾摇滚乐团，代表作《倔强》《突然好想你》", "aliases": ["五月天"]},
    {"name": "华晨宇", "category": "music", "desc": "内地男歌手，以高音与舞台表现力著称", "aliases": ["华晨宇"]},
    {"name": "毛不易", "category": "music", "desc": "内地创作歌手，代表作《消愁》《平凡的一天》", "aliases": ["毛不易"]},
    {"name": "周深", "category": "music", "desc": "内地歌手，以空灵音色与多语种翻唱著称", "aliases": ["周深"]},
    {"name": "许嵩", "category": "music", "desc": "内地创作型歌手，代表作《有何不可》《素颜》", "aliases": ["许嵩"]},
    {"name": "汪苏泷", "category": "music", "desc": "内地男歌手，代表作《一笑倾城》《万有引力》", "aliases": ["汪苏泷"]},
    {"name": "李荣浩", "category": "music", "desc": "内地创作型男歌手，代表作《模特》《李白》", "aliases": ["李荣浩"]},
    {"name": "张杰", "category": "music", "desc": "内地实力派男歌手，代表作《逆战》《天下》", "aliases": ["张杰"]},
    {"name": "单依纯", "category": "music", "desc": "内地新生代女歌手，嗓音细腻有辨识度", "aliases": ["单依纯"]},
    {"name": "陈粒", "category": "music", "desc": "内地独立女歌手，代表作《小半》《奇妙能力歌》", "aliases": ["陈粒"]},
    {"name": "房东的猫", "category": "music", "desc": "内地民谣女子组合，代表作《云烟成雨》", "aliases": ["房东的猫"]},
    {"name": "告五人", "category": "music", "desc": "台湾独立摇滚乐队，代表作《爱人错过》", "aliases": ["告五人"]},
    {"name": "万能青年旅店", "category": "music", "desc": "内地摇滚乐队，代表作《杀死那个石家庄人》", "aliases": ["万能青年旅店", "万青"]},
    {"name": "痛仰", "category": "music", "desc": "内地老牌摇滚乐队，代表作《公路之歌》", "aliases": ["痛仰"]},
    {"name": "新裤子", "category": "music", "desc": "内地摇滚乐队，代表作《没有理想的人不伤心》", "aliases": ["新裤子"]},
    {"name": "五条人", "category": "music", "desc": "内地独立乐队，用海丰话演唱风格独特", "aliases": ["五条人"]},
    {"name": "二手玫瑰", "category": "music", "desc": "内地摇滚乐队，东北秧歌混搭的独特风格", "aliases": ["二手玫瑰"]},

    # ---------------------------------------------------------- 音乐：海外与曲风
    {"name": "泰勒·斯威夫特", "category": "music", "desc": "美国创作型女歌手，粉丝都昵称她霉霉", "aliases": ["泰勒·斯威夫特", "taylor swift", "霉霉"]},
    {"name": "比莉·艾利什", "category": "music", "desc": "美国女歌手，风格低沉个性，昵称碧梨", "aliases": ["比莉·艾利什", "billie eilish", "碧梨"]},
    {"name": "防弹少年团", "category": "music", "desc": "韩国人气男子团体，英文简称 BTS，全球走红", "aliases": ["防弹少年团", "bts"]},
    {"name": "blackpink", "category": "music", "desc": "韩国人气女团，代表作《口哨》《像最后一样》", "aliases": ["blackpink"]},
    {"name": "iu", "category": "music", "desc": "韩国女歌手，音色细腻，代表作《好日子》", "aliases": ["iu"]},
    {"name": "米津玄师", "category": "music", "desc": "日本创作型歌手，代表作《柠檬》《打上花火》", "aliases": ["米津玄师"]},
    {"name": "yoasobi", "category": "music", "desc": "日本双人音乐组合，代表作《向夜晚奔去》", "aliases": ["yoasobi"]},
    {"name": "ado", "category": "music", "desc": "日本神秘系女歌手，代表作《唱》《烦死了》", "aliases": ["ado"]},
    {"name": "久石让", "category": "music", "desc": "日本配乐大师，吉卜力动画御用作曲家", "aliases": ["久石让"]},
    {"name": "坂本龙一", "category": "music", "desc": "日本作曲家，代表作《圣诞快乐劳伦斯先生》", "aliases": ["坂本龙一"]},
    {"name": "说唱", "category": "music", "desc": "跟着节拍念歌词的演唱曲风，也叫饶舌", "aliases": ["说唱", "rap"]},
    {"name": "摇滚", "category": "music", "desc": "摇滚乐风格，强调吉他失真与现场感", "aliases": ["摇滚"]},
    {"name": "民谣", "category": "music", "desc": "以叙事和木吉他伴奏为主的抒情曲风", "aliases": ["民谣"]},
    {"name": "古风", "category": "music", "desc": "融合传统乐器与文言意象的国风曲风", "aliases": ["古风", "国风"]},
    {"name": "电音", "category": "music", "desc": "电子舞曲曲风的统称，常被叫作电音", "aliases": ["电音", "edm"]},
    {"name": "爵士", "category": "music", "desc": "讲究即兴与摇摆节奏的曲风，常配器乐", "aliases": ["爵士", "jazz"]},
    {"name": "kpop", "category": "music", "desc": "韩国流行音乐的统称，以偶像团体为主", "aliases": ["kpop"]},
    {"name": "citypop", "category": "music", "desc": "上世纪日本都市流行曲风，复古惬意", "aliases": ["citypop"]},
    {"name": "livehouse", "category": "music", "desc": "小型的现场演出场地，常有乐队演出", "aliases": ["livehouse"]},
    {"name": "音乐节", "category": "music", "desc": "户外大型演出活动，如草莓音乐节、迷笛", "aliases": ["音乐节"]},
    {"name": "演唱会", "category": "music", "desc": "歌手举办的大型专场音乐演出活动", "aliases": ["演唱会"]},
    {"name": "翻唱", "category": "music", "desc": "重新演绎其他人的歌曲的演唱方式", "aliases": ["翻唱"]},
    {"name": "合唱", "category": "music", "desc": "两人或更多人一起演唱同一首歌曲", "aliases": ["合唱"]},
    {"name": "点歌", "category": "music", "desc": "观众点播歌曲，再由主播或现场演唱", "aliases": ["点歌"]},
    {"name": "伴奏", "category": "music", "desc": "没有主唱、专门供人跟唱的乐器声部", "aliases": ["伴奏"]},
    {"name": "声卡", "category": "music", "desc": "直播唱歌调音用的音频硬件设备之一", "aliases": ["声卡"]},
]
