"""影视类热门元素库：热播电视剧、电影、导演演员与名台词梗。"""

TOPICS = [
    # 国产热播剧
    {"name": "狂飙", "category": "tv", "desc": "2023 年扫黑题材国产剧，张颂文饰演高启强", "aliases": ["狂飙"]},
    {"name": "漫长的季节", "category": "tv", "desc": "2023 年悬疑剧，范伟秦昊主演东北碎尸案", "aliases": ["漫长的季节"]},
    {"name": "隐秘的角落", "category": "tv", "desc": "2020 年悬疑剧，秦昊主演，梗「一起去爬山吗」", "aliases": ["隐秘的角落"]},
    {"name": "沉默的真相", "category": "tv", "desc": "2020 年悬疑剧，廖凡白宇主演，改编自紫金陈小说", "aliases": ["沉默的真相"]},
    {"name": "庆余年", "category": "tv", "desc": "改编自猫腻小说的古装权谋剧，范闲为主角", "aliases": ["庆余年"]},
    {"name": "琅琊榜", "category": "tv", "desc": "胡歌主演古装权谋剧，梅长苏复仇翻案", "aliases": ["琅琊榜"]},
    {"name": "甄嬛传", "category": "tv", "desc": "孙俪主演经典清宫剧，宫斗题材巅峰之作", "aliases": ["甄嬛传"]},
    {"name": "知否知否应是绿肥红瘦", "category": "tv", "desc": "赵丽颖冯绍峰主演古装宅斗剧，改编自关心则乱小说", "aliases": ["知否知否应是绿肥红瘦", "知否"]},
    {"name": "都挺好", "category": "tv", "desc": "2019 年家庭剧，倪大红饰苏大强，爹味名场面", "aliases": ["都挺好"]},
    {"name": "人世间", "category": "tv", "desc": "2022 年年代剧，改编自梁晓声小说，周家三兄妹", "aliases": ["人世间"]},
    {"name": "繁花", "category": "tv", "desc": "王家卫执导，胡歌主演的上海年代剧", "aliases": ["繁花"]},
    {"name": "三体", "category": "tv", "desc": "刘慈欣科幻小说改编的国产剧，腾讯版", "aliases": ["三体"]},
    {"name": "开端", "category": "tv", "desc": "2022 年时间循环题材剧，白敬亭赵今麦主演", "aliases": ["开端"]},
    {"name": "苍兰诀", "category": "tv", "desc": "虞书欣王鹤棣主演的古装仙侠爱情剧", "aliases": ["苍兰诀"]},
    {"name": "星汉灿烂", "category": "tv", "desc": "吴磊赵露思主演古装剧，改编自关心则乱小说", "aliases": ["星汉灿烂"]},
    {"name": "莲花楼", "category": "tv", "desc": "成毅主演武侠悬疑剧，改编自藤萍小说", "aliases": ["莲花楼"]},
    {"name": "长相思", "category": "tv", "desc": "杨紫主演古装仙侠剧，改编自桐华小说", "aliases": ["长相思"]},
    {"name": "与凤行", "category": "tv", "desc": "赵丽颖林更新主演的古装仙侠爱情剧", "aliases": ["与凤行"]},
    {"name": "墨雨云间", "category": "tv", "desc": "吴谨言主演古装复仇爽剧，改编自小说", "aliases": ["墨雨云间"]},
    {"name": "玫瑰的故事", "category": "tv", "desc": "刘亦菲主演的都市女性成长题材剧", "aliases": ["玫瑰的故事"]},
    {"name": "我的阿勒泰", "category": "tv", "desc": "改编自李娟散文集的短剧，新疆风光", "aliases": ["我的阿勒泰"]},
    {"name": "边水往事", "category": "tv", "desc": "郭麒麟主演的边境悬疑剧，贩毒题材", "aliases": ["边水往事"]},
    {"name": "唐朝诡事录", "category": "tv", "desc": "古装探案剧，主角苏无名，取材唐代传说", "aliases": ["唐朝诡事录"]},
    {"name": "白夜追凶", "category": "tv", "desc": "潘粤明一人分饰双胞胎的刑侦悬疑剧", "aliases": ["白夜追凶"]},
    {"name": "老九门", "category": "tv", "desc": "陈伟霆赵丽颖主演盗墓题材剧，盗墓笔记前传", "aliases": ["老九门"]},
    {"name": "鬼吹灯", "category": "tv", "desc": "天下霸唱盗墓小说系列，含精绝古城等改编剧", "aliases": ["鬼吹灯"]},
    {"name": "盗墓笔记", "category": "tv", "desc": "南派三叔盗墓冒险小说系列及其改编剧", "aliases": ["盗墓笔记"]},
    {"name": "武林外传", "category": "tv", "desc": "2006 年古装情景喜剧，佟湘玉白展堂等角色", "aliases": ["武林外传"]},
    {"name": "家有儿女", "category": "tv", "desc": "经典家庭情景喜剧，刘星与夏雪夏雨", "aliases": ["家有儿女", "刘星"]},
    {"name": "西游记", "category": "tv", "desc": "四大名著改编神话剧，师徒四人取经", "aliases": ["西游记"]},
    {"name": "三国演义", "category": "tv", "desc": "四大名著改编的历史剧，94 版央视最经典", "aliases": ["三国演义", "三国"]},
    {"name": "水浒传", "category": "tv", "desc": "四大名著改编的剧，梁山一百零八将", "aliases": ["水浒传", "水浒"]},
    {"name": "亮剑", "category": "tv", "desc": "李幼斌主演经典抗战剧，李云龙梗多", "aliases": ["亮剑", "李云龙"]},
    {"name": "士兵突击", "category": "tv", "desc": "王宝强主演军旅剧，许三多「不抛弃不放弃」", "aliases": ["士兵突击", "许三多"]},
    {"name": "父母爱情", "category": "tv", "desc": "郭涛梅婷主演年代家庭剧，年代感强", "aliases": ["父母爱情"]},
    {"name": "大明王朝1566", "category": "tv", "desc": "经典历史剧，讲嘉靖与海瑞的朝堂博弈", "aliases": ["大明王朝1566", "大明王朝"]},
    {"name": "觉醒年代", "category": "tv", "desc": "讲新文化运动的革命历史剧，于和伟主演", "aliases": ["觉醒年代"]},
    {"name": "山海情", "category": "tv", "desc": "扶贫题材剧，讲西海固移民脱贫故事", "aliases": ["山海情"]},
    {"name": "大江大河", "category": "tv", "desc": "改革开放题材的剧，王凯饰演宋运辉", "aliases": ["大江大河"]},

    # 韩剧 / 日剧 / 美剧
    {"name": "鱿鱼游戏", "category": "tv", "desc": "韩剧，主角参加致命童年游戏闯关求生", "aliases": ["鱿鱼游戏", "squid game"]},
    {"name": "黑暗荣耀", "category": "tv", "desc": "宋慧乔主演韩剧，校园霸凌复仇题材", "aliases": ["黑暗荣耀"]},
    {"name": "顶楼", "category": "tv", "desc": "韩剧，讲述豪宅住户的狗血复仇故事", "aliases": ["顶楼"]},
    {"name": "爱的迫降", "category": "tv", "desc": "玄彬孙艺珍主演韩剧，南北韩爱情故事", "aliases": ["爱的迫降"]},
    {"name": "请回答1988", "category": "tv", "desc": "经典韩剧，双门洞邻里的温情群像剧", "aliases": ["请回答1988"]},
    {"name": "梨泰院class", "category": "tv", "desc": "朴叙俊主演的韩剧，复仇与创业题材", "aliases": ["梨泰院class", "梨泰院"]},
    {"name": "legal high", "category": "tv", "desc": "堺雅人主演日剧，毒舌律师古美门研介", "aliases": ["legal high", "李狗嗨"]},
    {"name": "半泽直树", "category": "tv", "desc": "堺雅人主演日剧，银行职场复仇爽剧", "aliases": ["半泽直树"]},
    {"name": "深夜食堂", "category": "tv", "desc": "日剧，讲述午夜小食堂里的温情故事", "aliases": ["深夜食堂"]},
    {"name": "孤独的美食家", "category": "tv", "desc": "日剧，井之头五郎探店的吃饭向作品", "aliases": ["孤独的美食家"]},
    {"name": "非自然死亡", "category": "tv", "desc": "石原里美主演日剧，法医题材职场剧", "aliases": ["非自然死亡", "unnatural"]},
    {"name": "逃避虽可耻但有用", "category": "tv", "desc": "新垣结衣主演日剧，契约结婚恋爱喜剧", "aliases": ["逃避虽可耻但有用"]},
    {"name": "老友记", "category": "tv", "desc": "经典美剧，六个好友的日常情景喜剧", "aliases": ["老友记", "friends"]},
    {"name": "生活大爆炸", "category": "tv", "desc": "经典美剧，谢尔顿等科学家室友的喜剧", "aliases": ["生活大爆炸", "谢尔顿"]},
    {"name": "权力的游戏", "category": "tv", "desc": "美剧，冰与火之歌改编的史诗奇幻剧", "aliases": ["权力的游戏", "权游", "冰与火之歌"]},
    {"name": "绝命毒师", "category": "tv", "desc": "美剧，讲化学老师沃尔特制毒成毒枭", "aliases": ["绝命毒师", "breaking bad"]},
    {"name": "怪奇物语", "category": "tv", "desc": "黑暗奇幻美剧，少年们对抗异世界怪物", "aliases": ["怪奇物语", "stranger things"]},
    {"name": "切尔诺贝利", "category": "tv", "desc": "美剧，还原切尔诺贝利核事故的灾难剧", "aliases": ["切尔诺贝利"]},
    {"name": "最后生还者", "category": "tv", "desc": "美剧，讲述末世中乔尔护送艾莉的冒险", "aliases": ["最后生还者", "the last of us"]},

    # 国产电影
    {"name": "让子弹飞", "category": "movie", "desc": "姜文执导黑色喜剧，名台词「让子弹飞一会儿」", "aliases": ["让子弹飞"]},
    {"name": "霸王别姬", "category": "movie", "desc": "张国荣张丰毅主演，讲京剧艺人的一生", "aliases": ["霸王别姬"]},
    {"name": "无间道", "category": "movie", "desc": "刘德华梁朝伟主演港片，警匪卧底经典", "aliases": ["无间道"]},
    {"name": "功夫", "category": "movie", "desc": "周星驰导演动作喜剧，包租婆等名角色", "aliases": ["功夫"]},
    {"name": "少林足球", "category": "movie", "desc": "周星驰执导电影，用少林武功踢足球", "aliases": ["少林足球"]},
    {"name": "大话西游", "category": "movie", "desc": "周星驰主演西游题材爱情悲剧，至尊宝", "aliases": ["大话西游", "至尊宝"]},
    {"name": "喜剧之王", "category": "movie", "desc": "周星驰主演，讲龙套演员的追梦故事", "aliases": ["喜剧之王"]},
    {"name": "美人鱼", "category": "movie", "desc": "周星驰导演的环保题材奇幻喜剧电影", "aliases": ["美人鱼"]},
    {"name": "西虹市首富", "category": "movie", "desc": "沈腾主演喜剧，讲述一夜暴富的考验", "aliases": ["西虹市首富"]},
    {"name": "夏洛特烦恼", "category": "movie", "desc": "沈腾马丽主演穿越喜剧，开心麻花作品", "aliases": ["夏洛特烦恼"]},
    {"name": "你好李焕英", "category": "movie", "desc": "贾玲导演主演，穿越回去见母亲的喜剧", "aliases": ["你好李焕英", "李焕英"]},
    {"name": "热辣滚烫", "category": "movie", "desc": "贾玲导演主演，讲减肥逆袭的励志片", "aliases": ["热辣滚烫"]},
    {"name": "流浪地球", "category": "movie", "desc": "郭帆导演科幻片，行星发动机推动地球", "aliases": ["流浪地球"]},
    {"name": "战狼", "category": "movie", "desc": "吴京自导自演军事动作片，冷锋主角", "aliases": ["战狼"]},
    {"name": "长津湖", "category": "movie", "desc": "吴京易烊千玺主演抗美援朝战争片", "aliases": ["长津湖"]},
    {"name": "我不是药神", "category": "movie", "desc": "徐峥主演，讲述仿制药与看病难话题", "aliases": ["我不是药神"]},
    {"name": "消失的她", "category": "movie", "desc": "朱一龙倪妮主演的悬疑片，结尾反转", "aliases": ["消失的她"]},
    {"name": "孤注一掷", "category": "movie", "desc": "反诈题材电影，讲境外网络诈骗故事", "aliases": ["孤注一掷"]},
    {"name": "第二十条", "category": "movie", "desc": "张艺谋导演，讲正当防卫的普法喜剧", "aliases": ["第二十条"]},
    {"name": "飞驰人生", "category": "movie", "desc": "韩寒导演的赛车题材喜剧片，沈腾主演", "aliases": ["飞驰人生"]},
    {"name": "唐人街探案", "category": "movie", "desc": "王宝强刘昊然主演的探案喜剧系列", "aliases": ["唐人街探案", "唐探"]},
    {"name": "封神", "category": "movie", "desc": "乌尔善导演神话史诗片，质子团出圈", "aliases": ["封神"]},
    {"name": "满江红", "category": "movie", "desc": "张艺谋导演悬疑喜剧，岳飞词为线索", "aliases": ["满江红"]},
    {"name": "长安三万里", "category": "movie", "desc": "国产动画电影，讲述李白高适的盛唐故事", "aliases": ["长安三万里"]},
    {"name": "哪吒之魔童降世", "category": "movie", "desc": "国产动画，颠覆哪吒形象的魔童设定", "aliases": ["哪吒之魔童降世", "哪吒", "哪咤"]},
    {"name": "大鱼海棠", "category": "movie", "desc": "国产动画电影，讲椿与鲲的奇幻故事", "aliases": ["大鱼海棠"]},
    {"name": "大圣归来", "category": "movie", "desc": "国产动画电影，孙悟空题材西游改编", "aliases": ["大圣归来"]},
    {"name": "白蛇缘起", "category": "movie", "desc": "国产动画，白娘子与许仙的前世故事", "aliases": ["白蛇缘起", "白蛇"]},
    {"name": "深海", "category": "movie", "desc": "国产动画电影，讲女孩参宿的深海梦境", "aliases": ["深海"]},
    {"name": "雄狮少年", "category": "movie", "desc": "国产动画电影，讲述舞狮少年的成长", "aliases": ["雄狮少年"]},
    {"name": "隐入尘烟", "category": "movie", "desc": "小众文艺片，讲述西北农村夫妻的相守", "aliases": ["隐入尘烟"]},
    {"name": "宇宙探索编辑部", "category": "movie", "desc": "伪纪录片式科幻喜剧，讲民科寻外星人", "aliases": ["宇宙探索编辑部"]},

    # 好莱坞 / 日韩电影
    {"name": "阿凡达", "category": "movie", "desc": "卡梅隆导演科幻片，潘多拉星球与纳美人", "aliases": ["阿凡达", "avatar"]},
    {"name": "复仇者联盟", "category": "movie", "desc": "漫威超级英雄集结电影，灭霸是反派", "aliases": ["复仇者联盟", "复联"]},
    {"name": "钢铁侠", "category": "movie", "desc": "漫威电影，小罗伯特唐尼饰托尼史塔克", "aliases": ["钢铁侠", "iron man"]},
    {"name": "蜘蛛侠", "category": "movie", "desc": "漫威超级英雄电影，能力越大责任越大", "aliases": ["蜘蛛侠", "spiderman", "spider-man"]},
    {"name": "蝙蝠侠", "category": "movie", "desc": "DC旗下超级英雄，哥谭首富布鲁斯韦恩", "aliases": ["蝙蝠侠", "batman"]},
    {"name": "蝙蝠侠黑暗骑士", "category": "movie", "desc": "诺兰执导蝙蝠侠电影，小丑是经典反派", "aliases": ["蝙蝠侠黑暗骑士", "黑暗骑士", "the dark knight"]},
    {"name": "星际穿越", "category": "movie", "desc": "诺兰科幻片，讲穿越虫洞寻找新家园", "aliases": ["星际穿越", "interstellar"]},
    {"name": "盗梦空间", "category": "movie", "desc": "诺兰执导科幻片，讲潜入梦境植入想法", "aliases": ["盗梦空间", "inception"]},
    {"name": "信条", "category": "movie", "desc": "诺兰执导科幻片，主打时间倒流设定", "aliases": ["信条", "tenet"]},
    {"name": "奥本海默", "category": "movie", "desc": "诺兰执导传记片，讲原子弹之父奥本海默", "aliases": ["奥本海默", "oppenheimer"]},
    {"name": "沙丘", "category": "movie", "desc": "维伦纽瓦执导科幻史诗片，讲沙漠星球", "aliases": ["沙丘", "dune"]},
    {"name": "疯狂的麦克斯", "category": "movie", "desc": "废土题材动作片，主打飙车与狂暴美学", "aliases": ["疯狂的麦克斯", "mad max"]},
    {"name": "疾速追杀", "category": "movie", "desc": "基努里维斯主演动作片，为爱犬复仇", "aliases": ["疾速追杀", "john wick"]},
    {"name": "黑客帝国", "category": "movie", "desc": "科幻片，讲人类困在虚拟世界的觉醒", "aliases": ["黑客帝国", "matrix"]},
    {"name": "指环王", "category": "movie", "desc": "奇幻史诗片，讲护送魔戒摧毁的故事", "aliases": ["指环王", "魔戒", "lotr"]},
    {"name": "哈利波特", "category": "movie", "desc": "魔法题材系列电影，主角哈利与霍格沃茨", "aliases": ["哈利波特", "harry potter"]},
    {"name": "加勒比海盗", "category": "movie", "desc": "奇幻冒险电影，杰克船长由德普主演", "aliases": ["加勒比海盗", "杰克船长"]},
    {"name": "速度与激情", "category": "movie", "desc": "飙车题材系列电影，主打家人与飞车", "aliases": ["速度与激情", "速激"]},
    {"name": "千与千寻", "category": "movie", "desc": "宫崎骏动画，讲少女千寻的神隐冒险", "aliases": ["千与千寻", "spirited away"]},
    {"name": "龙猫", "category": "movie", "desc": "宫崎骏动画，讲姐妹与龙猫的温情故事", "aliases": ["龙猫", "totoro"]},
    {"name": "哈尔的移动城堡", "category": "movie", "desc": "宫崎骏动画，讲述苏菲与哈尔的爱情", "aliases": ["哈尔的移动城堡", "哈尔"]},
    {"name": "铃芽之旅", "category": "movie", "desc": "新海诚动画，讲少女关闭灾难之门的旅程", "aliases": ["铃芽之旅", "铃芽户缔"]},
    {"name": "灌篮高手剧场版", "category": "movie", "desc": "井上雄彦电影，讲湘北对战山王工业", "aliases": ["灌篮高手剧场版", "the first slam dunk"]},
    {"name": "你的名字", "category": "movie", "desc": "新海诚动画，讲男女互换身体的相遇", "aliases": ["你的名字"]},
    {"name": "天气之子", "category": "movie", "desc": "新海诚动画，讲述少年与晴女的故事", "aliases": ["天气之子"]},
    {"name": "寄生虫", "category": "movie", "desc": "奉俊昊导演，讲贫富两个家庭的碰撞", "aliases": ["寄生虫", "parasite"]},
    {"name": "釜山行", "category": "movie", "desc": "韩国丧尸题材灾难电影，讲述列车求生", "aliases": ["釜山行", "train to busan"]},

    # 导演 / 演员
    {"name": "周星驰", "category": "movie", "desc": "香港喜剧巨星，代表作《功夫》《少林足球》", "aliases": ["周星驰", "星爷"]},
    {"name": "姜文", "category": "movie", "desc": "导演兼演员，代表作《让子弹飞》《鬼子来了》", "aliases": ["姜文"]},
    {"name": "张艺谋", "category": "movie", "desc": "中国第五代导演代表人物，执导《红高粱》", "aliases": ["张艺谋"]},
    {"name": "陈凯歌", "category": "movie", "desc": "中国第五代导演，代表作有《霸王别姬》", "aliases": ["陈凯歌"]},
    {"name": "宁浩", "category": "movie", "desc": "内地导演，代表作《疯狂的石头》《无人区》", "aliases": ["宁浩"]},
    {"name": "徐峥", "category": "movie", "desc": "演员兼导演，代表作《我不是药神》《泰囧》", "aliases": ["徐峥"]},
    {"name": "沈腾", "category": "movie", "desc": "开心麻花演员，喜剧电影的票房担当", "aliases": ["沈腾"]},
    {"name": "贾玲", "category": "movie", "desc": "喜剧演员兼导演，代表作《你好李焕英》", "aliases": ["贾玲"]},
    {"name": "吴京", "category": "movie", "desc": "动作演员导演，代表作《战狼》《流浪地球》", "aliases": ["吴京"]},
    {"name": "刘德华", "category": "movie", "desc": "香港四大天王之一，代表作《无间道》《天下无贼》", "aliases": ["刘德华", "华仔"]},
    {"name": "梁朝伟", "category": "movie", "desc": "香港著名影帝，代表作《花样年华》《色戒》", "aliases": ["梁朝伟"]},
    {"name": "周润发", "category": "movie", "desc": "香港著名演员，代表作《赌神》《英雄本色》", "aliases": ["周润发", "发哥"]},
    {"name": "成龙", "category": "movie", "desc": "功夫动作巨星，代表作《警察故事》《醉拳》", "aliases": ["成龙", "jackie chan"]},
    {"name": "李连杰", "category": "movie", "desc": "中国功夫演员，代表作《黄飞鸿》《少林寺》", "aliases": ["李连杰"]},
    {"name": "葛优", "category": "movie", "desc": "内地实力演员，代表作《活着》《让子弹飞》", "aliases": ["葛优"]},
    {"name": "黄渤", "category": "movie", "desc": "内地实力派演员，代表作《疯狂的石头》《斗牛》", "aliases": ["黄渤"]},
    {"name": "王宝强", "category": "movie", "desc": "演员导演，代表作《士兵突击》《唐人街探案》", "aliases": ["王宝强"]},
    {"name": "诺兰", "category": "movie", "desc": "英国导演，代表作《盗梦空间》《星际穿越》", "aliases": ["诺兰", "nolan"]},
    {"name": "卡梅隆", "category": "movie", "desc": "好莱坞导演，代表作《泰坦尼克号》《阿凡达》", "aliases": ["卡梅隆", "james cameron"]},
    {"name": "斯皮尔伯格", "category": "movie", "desc": "好莱坞著名导演，代表作《大白鲨》《辛德勒名单》", "aliases": ["斯皮尔伯格", "spielberg"]},
    {"name": "昆汀", "category": "movie", "desc": "好莱坞导演，代表作《低俗小说》《杀死比尔》", "aliases": ["昆汀", "tarantino"]},
    {"name": "宫崎骏", "category": "movie", "desc": "日本动画导演，吉卜力工作室代表人物", "aliases": ["宫崎骏", "miyazaki"]},
    {"name": "新海诚", "category": "movie", "desc": "日本动画导演，代表作《你的名字》《秒速五厘米》", "aliases": ["新海诚"]},
    {"name": "奉俊昊", "category": "movie", "desc": "韩国著名导演，代表作《寄生虫》《杀人回忆》", "aliases": ["奉俊昊"]},

    # 影视梗 / 名台词
    {"name": "我想吃鱼了", "category": "movie", "desc": "《狂飙》高启强名台词，暗示要动手搞事", "aliases": ["我想吃鱼了", "想吃鱼了"]},
    {"name": "爷青回", "category": "movie", "desc": "「爷的青春回来了」，怀旧经典内容时刷", "aliases": ["爷青回"]},
    {"name": "二营长", "category": "movie", "desc": "《亮剑》梗，二营长你他娘的意大利炮呢", "aliases": ["二营长", "意大利炮"]},
    {"name": "我全都要", "category": "movie", "desc": "《九品芝麻官》名台词，表示什么都想要", "aliases": ["我全都要"]},
    {"name": "耶稣也留不住他", "category": "movie", "desc": "《功夫》经典台词，形容谁也别想拦住他", "aliases": ["耶稣也留不住他"]},
    {"name": "退钱", "category": "movie", "desc": "源于国足采访的吐槽，泛指不值、快退钱", "aliases": ["退钱"]},
    {"name": "吃屎啦你", "category": "movie", "desc": "《旺角卡门》张学友台词，做表情包常用", "aliases": ["吃屎啦你", "食屎啦你"]},
    {"name": "9527", "category": "movie", "desc": "《唐伯虎点秋香》华府下人编号，周星驰梗", "aliases": ["9527"]},
    {"name": "面包会有的", "category": "movie", "desc": "经典台词「面包会有的」，指一切都会有的", "aliases": ["面包会有的"]},
    {"name": "你管这叫", "category": "movie", "desc": "吐槽句式「你管这叫」，表示离谱看不懂", "aliases": ["你管这叫"]},
    {"name": "我劝你善良", "category": "movie", "desc": "吐槽用语，劝对方别太过分或别乱说", "aliases": ["我劝你善良"]},
    {"name": "剧透", "category": "movie", "desc": "提前透露剧情关键内容，弹幕常喊别剧透", "aliases": ["剧透"]},
    {"name": "烂尾", "category": "movie", "desc": "指作品后期剧情崩坏、收尾让人失望", "aliases": ["烂尾"]},
    {"name": "神结局", "category": "movie", "desc": "指结局设计极其精彩、出人意料的说法", "aliases": ["神结局"]},
    {"name": "下饭剧", "category": "movie", "desc": "适合边吃饭边看的轻松不烧脑的剧", "aliases": ["下饭剧"]},
    {"name": "电子榨菜", "category": "movie", "desc": "指吃饭时必看的剧综，堪称下饭伴侣", "aliases": ["电子榨菜"]},
    {"name": "烂片", "category": "movie", "desc": "质量差、口碑崩坏的电影，往往叫烂片", "aliases": ["烂片"]},
    {"name": "爆米花电影", "category": "movie", "desc": "指轻松爽快、无需动脑的商业娱乐片", "aliases": ["爆米花电影"]},
]
